export const COLORS = {
	INFO: 'INFO',
	ERROR: 'ERROR',
	WARNING: 'WARNING',
	SUCCESS: 'SUCCESS',
	TIP: 'TIP',
	DARK: 'DARK',
	LIGHT: 'LIGHT',
	TRANSPARENT: 'TRANSPARENT',
	PRIMARY: 'PRIMARY',
	DISABLED_BACKGROUND: 'DISABLED_BACKGROUND',
	DISABLED_FOREGROUND: 'DISABLED_FOREGROUND',
	SHADOW: 'SHADOW',
	LAYER: 'LAYER',
};

export const DEFAULT_COLOR = COLORS.PRIMARY;
